### PR TITLE
RFC4122 Time-Based Version 1 UUID Generation

### PR DESCRIPTION
**Pull request by SomeshDaga**
* This provides an implementation for the RFC4122 Time-Based Version 1 Standard as described https://tools.ietf.org/html/rfc4122#section-4.2

### CODE REVIEW

**Comment by jack-oquin** [comment]
It would be nice to add a time-based implementation to the Python interface, as well. There *is* a uuid1 implementation available.

**Comment by SomeshDaga** [comment]
@jack-oquin thanks for the heads up on the uuid1 implementation. Gave me an opportunity to compare with the results of my C++ implementation. Have added it to the python interface as well

**Comment by tfoote** [comment]
@SomeshDaga a few unit tests would be really great to be confident that this will keep working correctly with future updates. Since these are free functions they're relatively easy to test and there are some good examples already that you could copy from the other functions.

**Comment by SomeshDaga** [comment]
@tfoote Some tests have been added. I would like to add that the generation of the clock_id which is part of the uuid, is done using a random number generator. This puts an onus on the user to seed the generator, which has been documented in the docstring. If it is not seeded, it will use the default seed which is typically updated on the order of a second. This should work for most usage scenarios I can envision. Let me know what you think

**Comment by jack-oquin** [comment]
This looks good to me.

@mikaelarguedas: would you look this over, checking for any ROS2 migration issues?

**Comment by mikaelarguedas** [comment]
this looks good to me.
@tfoote would have the most context as of how to convert ROS1's `ros::Time` to a ROS2 version (can this simply be changed to a `builtin_interfaces/Time` structure?)

**Comment by jack-oquin** [comment]
@mikaelarguedas: I don't believe ``builtin_interfaces`` exists in ROS1. I don't understand the intended migration path for ``ros::Time`` to ROS2. Presumably, some people have thoughts about it.

**Comment by tfoote** [comment]
We have not fullly developed the migration path for Time. The 1 to 1 mapping right now for `builtin_messages/Time` is `std_msgs/Time` and we recently [removed the special aspects](https://github.com/ros2/rmw_opensplice/pull/217) of `builtin_msgs` so they can be reintegrated as plain messages. There are also the C and C++ native datatypes to consider supporting. Likely a templated time adapter would be the best way to have portable code between ROS and ROS2. For this change I think that this is out of scope though.

**Comment by jack-oquin** [comment]
@SomeshDaga: Thanks for contributing!

**Pull request merged**
