### PR TITLE
convert to package format 2

### PR DESCRIPTION
**Pull request by mikaelarguedas**
As per title. This doesn't change any of the dependencies, only update to package format 2

### CODE REVIEW

**Comment by jack-oquin** [comment]
Fine with me.

If you want to expedite this change, please consider submitting a pull request.

**Comment by mikaelarguedas** [comment]
@jack-oquin 
> please consider submitting a pull request

Could you point out to what changes are necessary to this pull request ? I'd be happy to update it accordingly

**Comment by jack-oquin** [comment]
D'oh! I mistook this message for an issue. Your change looks good to me.

Thanks for contributing!

**Comment by jack-oquin** [comment]
Do you want a new binary release for this, or is the source change sufficient?

**Comment by mikaelarguedas** [comment]
The source change is sufficient for now, I opened if mostly so that https://github.com/ros2/unique_identifier/issues/1 could reuse the change rather than duplicating it.

Thanks!

**Comment by jack-oquin** [comment]
Sounds good. I won't release it yet. There may be other ROS2 changes that can be back-ported to minimize the differences.

I find it discouraging that there were so many incompatibilities in such a small, simple component.

**Comment by mikaelarguedas** [comment]
The PR to move it to ROS2 indeed introduces more changes than necessary, and I agree with you that some of the necessary changes should be upstreamed to keep the diff minimal (this PR porting to format 2 being a first step in that direction). I'll comment on the other PR for specific questions.

Another way to keep the diff manageable and to easily forward/backport changes would be to host and maintain a ROS2 version of this packages on a `ros2` branch of this repository rather than an arbitrary fork. Would it be something that you are interested in ?

**Comment by jack-oquin** [comment]
Since I'm not actively working on ROS2, it would be hard for me to maintain a ``ros2`` branch without either breaking it or taking on a significant additional commitment.

Would you be willing to co-maintain it? That might make sense.

**Comment by mikaelarguedas** [comment]
I'm happy to give a hand for the initial port and the maintenance for a while. This package being pretty low activity, the maintenance burden should (hopefully) not be too heavy. I'd love that maintainers of the ROS 1 packages stay as involved as possible in the ROS 2 version because they have the best knowledge of the code base and it will make it much easier to prevent the 2 versions from diverging.
Does that make sense?

**Comment by jack-oquin** [comment]
Yes. That's OK with me. I invited you to join the developers team. You should get an e-mail about that.

Once you have joined, go ahead and create a ``ros2`` branch and bring it up to date with whatever commits you feel are appropriate.

**Pull request merged**
